name: Host System Builder

on:
  push:
    paths:
      - "**.c"
      - "**.cpp"
      - "**.h"
  pull_request:
    paths:
      - "**.h"
      - "**.h"

jobs:

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3.0.0
    - uses: actions/setup-python@v2.3.2
      with:
        python-version: '3.9.x'
    - run: pip install meson ninja scan-build
    - run: brew install ccache cppcheck
    - run: meson setup build -Dwith_tests=enabled
      env:
        CC: ccache gcc
        CXX: ccache g++
    - run: cppcheck --project=build/compile_commands.json
    - run: scan-build meson test -C build -v

    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: MacOS_Meson_Testlog
        path: build/meson-logs/testlog.txt

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3.0.0
    - uses: actions/setup-python@v2.3.2
      with:
        python-version: '3.9.x'        
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: ccache gcc
    - run: pip install meson ninja
    - run: meson setup build -Dwith_tests=enabled
      env:
        CC: ccache gcc
        CXX: ccache g++
    - run: meson test -C build -v
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: Windows_Meson_Testlog
        path: build/meson-logs/testlog.txt

  chrome_book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.0
    - uses: nanasess/setup-chromedriver@v1.0.5
    - run: chromedriver --url-base=/wd/hub &
    - run: |
        sudo apt-get install python3 python3-pip gcc g++ cppcheck ccache -y &&
        python3 -m pip install meson ninja
    - run: |
        meson setup build -Dwith_tests=enabled &&
        cppcheck --project=build/compile_commands.json &&
        meson test -C build -v

  ubuntu_linux:
    runs-on: ubuntu-latest
    container:
      image: "michaelbrockus/ubuntu-host:latest"
    steps:
    - uses: actions/checkout@v3.0.0
    - run: |
        meson setup build -Dwith_tests=enabled &&
        cppcheck --project=build/compile_commands.json &&
        meson test -C build -v
      working-directory: .
 
  debian_linux:
    runs-on: ubuntu-latest
    container:
      image: "michaelbrockus/debian-host:latest"
    steps:
    - uses: actions/checkout@v3.0.0
    - run: |
        meson setup build -Dwith_tests=enabled &&
        cppcheck --project=build/compile_commands.json &&
        meson test -C build -v
      working-directory: .

  fedora_linux:
    runs-on: ubuntu-latest
    container:
      image: "michaelbrockus/fedora-host:latest"
    steps:
    - uses: actions/checkout@v3.0.0
    - run: |
        meson setup build -Dwith_tests=enabled &&
        cppcheck --project=build/compile_commands.json &&
        meson test -C build -v
      working-directory: .

  arch_linux:
    runs-on: ubuntu-latest
    container:
      image: "michaelbrockus/archlinux-host:latest"
    steps:
    - uses: actions/checkout@v3.0.0
    - run: |
        meson setup build -Dwith_tests=enabled &&
        cppcheck --project=build/compile_commands.json &&
        meson test -C build -v
      working-directory: .
